version: '3'
services:
  app:
    container_name: must_buy_php
    build: ./php
    tty: true
    volumes:
      - ./work:/var/www/html
    ports:
      - 80:80
    network_mode: "mynetwork"

  db:
    container_name: must_buy_mysql
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: must_buy_app_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: pass
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/mysql_conf:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    network_mode: "mynetwork"
  
volumes:
    mysql_data:

networks:
  mynetwork:
